const actions = {
    ru: { updated: 'Изменение', created: 'Создание', deleted: 'Удаление', saved: 'Сохранение', login: 'Вход', logout: 'Выход', restored: 'Восстановление', attached: 'Прикрепление', detached: 'Открепление', generated: 'Генерация', regenerated: 'Перегенерация', exported: 'Выгрузка', downloaded: 'Скачивание', accepted: 'Принятие', sent: 'Отправка', deactivated: 'Деактивация', reordered: 'Изменение порядка', ready: 'Завершено', queued: 'В очереди', processing: 'Выполняется', expired: 'Истёк срок', score_updated: 'Изменение оценки', winner_updated: 'Выбор победителя', absences_updated: 'Изменение неявок', tatami_updated: 'Изменение татами', status_updated: 'Изменение статуса', student_list_moved: 'Перенос в список', dates_rescheduled: 'Перенос дат' },
    en: { updated: 'Updated', created: 'Created', deleted: 'Deleted', saved: 'Saved', login: 'Signed in', logout: 'Signed out', restored: 'Restored', attached: 'Attached', detached: 'Detached', generated: 'Generated', regenerated: 'Regenerated', exported: 'Exported', downloaded: 'Downloaded', accepted: 'Accepted', sent: 'Sent', deactivated: 'Deactivated', reordered: 'Reordered', ready: 'Completed', queued: 'Queued', processing: 'Processing', expired: 'Expired', score_updated: 'Score updated', winner_updated: 'Winner selected', absences_updated: 'Absences updated', tatami_updated: 'Tatami updated', status_updated: 'Status updated', student_list_moved: 'Moved to another list', dates_rescheduled: 'Dates rescheduled' },
};
export function activityAction(event, locale) {
    if (event === 'student.coach.joined') return locale === 'ru' ? 'Присоединение к тренеру' : 'Joined a coach';
    const key = (event ?? '').toLowerCase().split('.').pop();
    return actions[locale][key] || event;
}
export const activityFields = {
    ru: { name: 'Название', first_name: 'Имя', last_name: 'Фамилия', email: 'Email', weight: 'Вес', height: 'Рост', birthday: 'Дата рождения', rang: 'Кю / дан', gender: 'Пол', club: 'Клуб', region_id: 'Регион', coach_id: 'Тренер', organization_id: 'Организация', title: 'Название', text: 'Текст', description: 'Русский текст', description_en: 'Английский текст', price: 'Стоимость', date: 'Дата начала', date_finish: 'Дата окончания', date_commission: 'Дата комиссии', can_edit_students: 'Правки учениками', can_edit_coaches: 'Правки тренерами', updated_at: 'Дата изменения', created_at: 'Дата создания', path: 'Видео', poster_path: 'Обложка' },
    en: { name: 'Name', first_name: 'First name', last_name: 'Last name', email: 'Email', weight: 'Weight', height: 'Height', birthday: 'Date of birth', rang: 'Kyu / dan', gender: 'Gender', club: 'Club', region_id: 'Region', coach_id: 'Coach', organization_id: 'Organization', title: 'Title', text: 'Text', description: 'Russian text', description_en: 'English text', price: 'Price', date: 'Start date', date_finish: 'Finish date', date_commission: 'Commission date', can_edit_students: 'Student editing', can_edit_coaches: 'Coach editing', updated_at: 'Updated at', created_at: 'Created at', path: 'Video', poster_path: 'Cover' },
};
